version: '3'
services:
  nginx:
    image: "brainstormwilly/fullstack-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
  server:
    image: "brainstormwilly/fullstack-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: "brainstormwilly/fullstack-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "brainstormwilly/fullstack-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT